In [3]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

## Mandatory assignment 1
### STK-IN4300
### Jørn Eirik Betten

### The Data Set 
I decided to take a closer look at the Wisconsin Breast Cancer data set, which can be downloaded from [WBCData](https://archive-beta.ics.uci.edu/ml/datasets/breast+cancer+wisconsin+diagnostic).

In [4]:
# Adding path to location where I stored the data.
path ="/home/jeb/Documents/STKIN4300/MAs/MA1/data/WBCData/"

In [14]:
filename = "breast-cancer-wisconsin.data"
col_names = ["ID", "clump_thickness", "cell_size_uniformity", "cell_shape_uniformity", "marginal_adhesion", 
             "SE_cell_size", "bare_nuclei", "bland_chromatin", "normal_nucleoli", "mitoses", "target"]
data = pd.read_csv(path + filename)
data.columns = col_names 
data

,ID,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,SE_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,target
0,1002945,5,4,4,5,7,10,3,2,1,2
1,1015425,3,1,1,1,2,2,3,1,1,2
2,1016277,6,8,8,1,3,4,3,7,1,2
3,1017023,4,1,1,3,2,1,3,1,1,2
4,1017122,8,10,10,8,7,10,9,7,1,4
...,...,...,...,...,...,...,...,...,...,...,...
693,776715,3,1,1,1,3,2,1,1,1,2
694,841769,2,1,1,1,2,1,1,1,1,2
695,888820,5,10,10,3,7,3,8,10,2,4
696,897471,4,8,6,4,3,4,10,6,1,4
697,897471,4,8,8,5,4,5,10,4,1,4

In [61]:
data = data.replace("?", np.nan)


for name in col_names: 
    if name == "ID": 
        print("ID is just the patient number. Moving on..")
    elif name == "target": 
        
        num_mal_tumors = data[data["target"]==4].count() 
        num_ben_tumors = data[data["target"]==2].count()
        
        print(f"The data set contains {num_mal_tumors[0]} people with malignent tumors,")
        print(f"and {num_ben_tumors[0]} people with benign tumors.")
        
    else: 
        col = data[name].astype(float)
        mean = col.mean()
        std = col.std()
        median = col.median()
        q1 = col.quantile(0.25)
        q3 = col.quantile(0.75)
        minimum = col.min()
        maximum = col.max()
        print(f"{name}:\n mean={mean:.1f} +-{std:.1f}, \n median={median:.2f}({q1:.2f}-{q3:.2f}),\n min-max =({minimum:.0f}-{maximum:.0f})")

ID is just the patient number. Moving on..
clump_thickness:
 mean=4.4 +-2.8,
 median=4.00(2.00-6.00),
 min-max =(1-10)
cell_size_uniformity:
 mean=3.1 +-3.1,
 median=1.00(1.00-5.00),
 min-max =(1-10)
cell_shape_uniformity:
 mean=3.2 +-3.0,
 median=1.00(1.00-5.00),
 min-max =(1-10)
marginal_adhesion:
 mean=2.8 +-2.9,
 median=1.00(1.00-4.00),
 min-max =(1-10)
SE_cell_size:
 mean=3.2 +-2.2,
 median=2.00(2.00-4.00),
 min-max =(1-10)
bare_nuclei:
 mean=3.5 +-3.6,
 median=1.00(1.00-6.00),
 min-max =(1-10)
bland_chromatin:
 mean=3.4 +-2.4,
 median=3.00(2.00-5.00),
 min-max =(1-10)
normal_nucleoli:
 mean=2.9 +-3.1,
 median=1.00(1.00-4.00),
 min-max =(1-10)
mitoses:
 mean=1.6 +-1.7,
 median=1.00(1.00-1.00),
 min-max =(1-10)
The data set contains 241 people with malignent tumors,
and 457 people with benign tumors.

In [62]:
241 + 457

698